name: Library System Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black
    - name: Check formatting with Black
      continue-on-error: true
      run: |
        black . --check
    - name: Run tests
      run: |
        python -m pytest tests.py -v